### ISSUE TITLE
Elation: Chart notes

### ISSUE THREAD

**Issue by bejoinka** [awell-health/awell-extensions#99]
![image](https://user-images.githubusercontent.com/19916684/233528223-1daa73f9-d4f0-47da-83f9-a62d4b5804dc.png)

# Chart Notes

The [non-visit note](https://docs.elationhealth.com/reference/the-non-visit-note-object) is a special kind of note that, as the name suggests, is not associated with a visit. These notes, in their simplest form, provide a chronological account of information about the patient. While they can be plain text, they can also contain vitals and links to other documents.

## The use case for Non-Visit Notes

- Patient books appointment (or patient is created)
- Triggers a webhook (coming soon...)
- we start a flow
- We send text message with hosted pages link
- Patient fills in some form in hosted pages
- Data is piped back to Elation as a note

My understanding is that non-visit notes are the most appropriate format for this sort of information.

## Tasks
- [x] Create a non-visit note
- [x] Update a non-visit note
- [x] Get a non-visit note
- [x] Delete a non-visit note (to complete CRUD functionality)

## Details
In terms of how we want to handle, the goal here will be to **not mutate the required object, but instead omit items we can't support**. So, we'll support `tags` as an array of ints. we won't support `note_documents` or `note_items` yet.

The one exception is going to be `bullets`. We're going to have to support that, because that's where the note is. Here, we'll just support a single note:
![image](https://user-images.githubusercontent.com/19916684/233533757-d362deab-3cc1-4451-87e6-34f56d9f210e.png)
- category will always be 'Problem'
- Author is equivalent to `physicianUserId` (see #107 ) 
- text is the note itself.

## What's missing?
Normally, the note is used for historical documents from other doctors. "Hey, you've got your old charts? we'll log them as non-visit notes, add them as documents, and include bullets to summarize the documents."- 

That's the normal use case :point_up: ... but, we're going to be using these as a way to log inputs from forms.

If we get feedback from customers that the non-visit note is not the best way to use these notes, we'll make adjustments and perhaps add some other way to perform this use case... but that's where we're starting for now.

**Comment by bejoinka** [comment]
Quick note: i put #107 ahead of this one because we will use the `physicianUserId` from the `Find Physician` action in order to populate the `author` field of the chart note. these should correspond in field/datapoint type
